debug: false
spring:
  datasource:
    password: webflash190602
    sql-script-encoding: utf-8
    url: jdbc:mysql://localhost:3306/webflash?useUnicode=true&characterEncoding=UTF8
    username: webflash
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
